services:
  app:                                 # <<< ONE container for web+api
    build:
      context: .
      dockerfile: Dockerfile
      target: debug                   # <-- use the debug stage
    env_file: .env
    environment:
      - DatabaseProvider=PostgreSQL
      - ConnectionStrings__PostgresConnection=Host=postgres;Port=5432;Database=homedashboard;Username=homedashboarduser;Password=homedashboardpassword
      - FrontUrl=https://localhost,https://localhost:8443
      - ASPNETCORE_URLS=http://0.0.0.0:8080
    expose:
      - "8080"                        # internal HTTP
      # 4024 no longer needed; using docker exec attach
    # ports:                         # not needed for debugger with docker exec
    #   - "4024:4024"                # allow VS Code attach (deprecated)
    volumes:
      - db_data:/app/data
    depends_on:
      postgres:
        condition: service_healthy

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app

  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: homedashboard
      POSTGRES_USER: homedashboarduser
      POSTGRES_PASSWORD: homedashboardpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U homedashboarduser -d homedashboard"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:
  caddy_data:
  caddy_config:
  postgres_data:
